### ISSUE TITLE
cern-roll installation problem

### ISSUE THREAD

**Issue by ivannovikov** [sdsc/cern-roll#2] opened 2016-05-25 18:06 UTC
Hello,

We are having difficulties with cern-roll installation:
- cern-roll is getting installed on a cluster under Rocks version 6.2.
- The following rolls were installed:
  ganglia: 6.2, x86_64
  kernel: 6.2 x86_64
  hpc: 6.2 x86_64
  perfSONAR: 3.4.2 x86_64
  web-server: 6.2 x86_64
  python: 6.2 x86_64
  java: 6.2 x86_64
  base: 6.2 x86_64
  perl: 6.2 x86_64
  sge: 6.2 x86_64
  os: 6.2 x86_64
  sdsc: master.0  x86_64
  cmake: master.0 x86_64
  gnucompiler: master.0 x86_64
- All tests for sdsc, cmake and gnucompiler rolls returned "OK"
- When we install cern-roll, the system is getting “frozen” during make stage, i.e. during executing make 2>&1 | tee build.log.
  Last line in build.log looks like:

[52%] Building CXX object CMakeFiles/CLHEP.dir/Random/src

After that the system just “hangs” there for hours/days.

Any suggestion would be greatly appreciated.

Thank you,
Ivan

**Comment by jjhayes** [comment] 2016-05-25 21:41
Hi Ivan,

I saw your posting yesterday on the Rocks m/l.  I've been unable to reproduce this problem in my build, and I'm not sure what to suggest.  You might try building the clhep rpm separately to see if the results are any different.  From the cern-roll root directory, do

`make distclean`
`cd src/clhep`
`make rpm`

Also, before you start the build, make sure that `module list` indicates that no modulefiles are loaded.  Loaded modulefiles can sometimes set up your environment in ways that cause problems with roll builds.

Jim

**Comment by ivannovikov** [comment] 2016-05-26 18:18
Jim,

I've done all of those steps you mentioned:
1. module list
   No Modulefiles Currently Loaded.
2. make distclean 
   cd src/clhep 
   make rpm

All seemed to go through fast and without error messages. 

How can I test it now: Do I understad correctly that this: /root/rolltests/cern.t  won't work?
Also, cern-roll documentation mentiones that:

"In addition to the software itself, the roll installs cern environment module files in:
/opt/modulefiles/applications/cern"

Should we do something about that?

Thank you,
Ivan

**Comment by jjhayes** [comment] 2016-05-26 18:51
Interesting.  That doesn't indicate what your original problem was, but it likely eliminates the clhep build process as a suspect.  With "make rpm" successfully completed, you should find the sdsc-clhep rpm in cern-roll/RPMS/x86_64/.

Next, I'd try "make rpm" in each of the other src/ subdirectories--cern-modules, geant, roll-test, and root.  (_Don't_ do a make-distclean beforehand, or you'll lose what's already been built.)  If those succeed, then you can install the rpms directly (`cd cern-roll/RPMS/x86_64; rpm -i *.rpm`), after which /root/rolltests/cert.t should run successfully.

If all that works, and building the roll from the top level continues to hang, you might look carefully through the portion of build.log that gets produced before the build stops to see if there are any error/warning messages that might give clues to the source of the problem.

Jim

**Comment by ivannovikov** [comment] 2016-05-27 17:52
Jim,

When we tried "make rpm" in /src/geant directory, the following message appeares: 

::: Downloading http://forge.sdsc.edu/triton/cern-roll-master/src/geant/geant4.10.01.tar.gz :::
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
::: Verifying size of geant4.10.01.tar.gz :::
/usr/bin/stat: cannot stat `geant4.10.01.tar.gz': No such file or directory

Ivan

**Comment by jerrypgreenberg** [comment] 2016-05-27 18:01
Ivan,

If you are building an individual rpm and the source has not been downloaded, you have to do the following:

make ROLLNAME=cern build

In order to get the correct download url

(in the case clhep, you must have already had the tar files in the directory)

Jerry

**Comment by jjhayes** [comment] 2016-05-27 18:03
Sorry; I forgot that the other sources wouldn't have already been downloaded.  Try `make ROLLNAME=cern rpm`.  The ROLLNAME value is generated automatically when building from the top level, but needs to be supplied directly during this sort of debugging.

Jim

**Comment by ivannovikov** [comment] 2016-05-27 19:35
Dear All,

Thank you for suggestions.

We've done:
1. in /src/geant
make ROLLNAME=cern build
make rpm

No error messages
1. In /src/root

make ROLLNAME=cern build
make rpm
...
...
collect2: error: ld returned 1 exit status
make[3]: **\* [bin/rootcling] Error 1
make[3]: **\* Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make[3]: **\* [lib/libCling.so] Error 1
make[3]: Leaving directory `/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05'
make[2]: *** [build] Error 2
make[2]: Leaving directory`/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05'
make[1]: **\* [build] Error 2
make[1]: Leaving directory `/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05'
error: Bad exit status from /var/tmp/rpm-tmp.Cuitn0 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Cuitn0 (%build)
make: **\* [rpm] Error 1

Ivan

**Comment by jjhayes** [comment] 2016-05-27 19:42
What comes just before that "collect2: error..." message?  It sounds like there should be some indication of a missing library.

Jim

**Comment by ivannovikov** [comment] 2016-05-27 19:47
==> lib/libvectorDict.so done
==> lib/libGLEW.so done
==> lib/libRIO.so done
g++ -shared -Wl,-soname,libCling.so -m64 -O2 -DNDEBUG -Wl,--no-undefined -Wl,--as-needed -o lib/libCling.so core/meta/src/TCling.o core/meta/src/TClingBaseClassInfo.o core/meta/src/TClingCallFunc.o core/meta/src/TClingCallbacks.o core/meta/src/TClingClassInfo.o core/meta/src/TClingDataMemberInfo.o core/meta/src/TClingMethodArgInfo.o core/meta/src/TClingMethodInfo.o core/meta/src/TClingTypeInfo.o core/meta/src/TClingTypedefInfo.o core/meta/src/TClingValue.o core/metautils/src/BaseSelectionRule.o core/metautils/src/ClassSelectionRule.o core/metautils/src/VariableSelectionRule.o core/metautils/src/RStl.o core/metautils/src/Scanner.o core/metautils/src/SelectionRules.o core/metautils/src/XMLReader.o core/metautils/src/TMetaUtils.o interpreter/cling/lib/Interpreter/AutoSynthesizer.o interpreter/cling/lib/Interpreter/AutoloadCallback.o interpreter/cling/lib/Interpreter/BackendPass.o interpreter/cling/lib/Interpreter/CIFactory.o interpreter/cling/lib/Interpreter/CheckEmptyTransactionTransformer.o interpreter/cling/lib/Interpreter/ClangInternalState.o interpreter/cling/lib/Interpreter/DeclCollector.o interpreter/cling/lib/Interpreter/DeclExtractor.o interpreter/cling/lib/Interpreter/DynamicExprInfo.o interpreter/cling/lib/Interpreter/DynamicLibraryManager.o interpreter/cling/lib/Interpreter/DynamicLookup.o interpreter/cling/lib/Interpreter/ForwardDeclPrinter.o interpreter/cling/lib/Interpreter/IncrementalExecutor.o interpreter/cling/lib/Interpreter/IncrementalParser.o interpreter/cling/lib/Interpreter/Interpreter.o interpreter/cling/lib/Interpreter/InterpreterCallbacks.o interpreter/cling/lib/Interpreter/InvocationOptions.o interpreter/cling/lib/Interpreter/LookupHelper.o interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.o interpreter/cling/lib/Interpreter/RequiredSymbols.o interpreter/cling/lib/Interpreter/RuntimeException.o interpreter/cling/lib/Interpreter/Transaction.o interpreter/cling/lib/Interpreter/TransactionTransformer.o interpreter/cling/lib/Interpreter/TransactionUnloader.o interpreter/cling/lib/Interpreter/Value.o interpreter/cling/lib/Interpreter/ValueExtractionSynthesizer.o interpreter/cling/lib/Interpreter/ValuePrinter.o interpreter/cling/lib/Interpreter/ValuePrinterSynthesizer.o interpreter/cling/lib/MetaProcessor/Display.o interpreter/cling/lib/MetaProcessor/InputValidator.o interpreter/cling/lib/MetaProcessor/MetaLexer.o interpreter/cling/lib/MetaProcessor/MetaParser.o interpreter/cling/lib/MetaProcessor/MetaProcessor.o interpreter/cling/lib/MetaProcessor/MetaSema.o interpreter/cling/lib/Utils/AST.o -L/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/interpreter/llvm/inst/lib -lclangFrontend -lclangSerialization -lclangDriver -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangAST -lclangEdit -lclangLex -lclangBasic -lLLVMProfileData -lLLVMObjCARCOpts -lLLVMInstrumentation -lLLVMipo -lLLVMVectorize -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMJIT -lLLVMExecutionEngine -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMTarget -lLLVMMC -lLLVMBitWriter -lLLVMCore -lLLVMSupport -L/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/interpreter/llvm/inst/lib -lz -lpthread -ltinfo -lrt -ldl -lm -Llib -lRIO -Llib -lCore -ldl
collect2: error: ld returned 1 exit status
make[3]: **\* [bin/rootcling] Error 1
make[3]: **\* Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make[3]: **\* [lib/libCling.so] Error 1
make[3]: Leaving directory `/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05'
make[2]: *** [build] Error 2
make[2]: Leaving directory`/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05'
make[1]: **\* [build] Error 2
make[1]: Leaving directory `/root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05'
error: Bad exit status from /var/tmp/rpm-tmp.Cuitn0 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Cuitn0 (%build)
make: **\* [rpm] Error 1

**Comment by jjhayes** [comment] 2016-05-27 20:00
Hmmm....  That doesn't really explain the error, does it?

Do you get any additional information if you `cd /root/Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05` and copy/paste that g++ link to the command line?

**Comment by ivannovikov** [comment] 2016-05-27 20:22
Jim,

We executed g++ command from /Downloads/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05

Message ending looks like that:

DynamicLibraryManager.cpp:(.text+0x1e3a): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.o: In function`cling::IfStmtInjector::VisitCallExpr(clang::CallExpr_)':
NullDerefProtectionTransformer.cpp:(.text._ZN5cling14IfStmtInjector13VisitCallExprEPN5clang8CallExprE[cling::IfStmtInjector::VisitCallExpr(clang::CallExpr_)]+0x44b): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/bin/ld: final link failed: No space left on device
collect2: ld returned 1 exit status

I am not sure how to understand this message. Disk Usage Analyzer says that Total filesystem capacity: 144.5 GB (used: 19.2 GB available: 125.3 GB).

Regards,
Ivan

**Comment by jjhayes** [comment] 2016-05-27 20:50
That message at least gives a clue.  Maybe the build is trying to write to /tmp and the partition is full?

Jim

**Comment by ivannovikov** [comment] 2016-05-27 20:56
How could we check it?

Ivan

**Comment by jjhayes** [comment] 2016-05-27 20:57
What does "df -h" show?

**Comment by ivannovikov** [comment] 2016-05-27 20:58
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        16G   16G     0 100% /
tmpfs           4.0G  8.0K  4.0G   1% /dev/shm
/dev/sda5       126G  3.4G  116G   3% /state/partition1
/dev/sda2       3.8G  673M  3.0G  19% /var
tmpfs           2.0G   16M  1.9G   1% /var/lib/ganglia/rrds

**Comment by jjhayes** [comment] 2016-05-27 21:00
Yep--looks like your / partition is full.  Try doing an `ls -lSr /tmp` and clearing out some of the larger files before restarting the build.

Jim

**Comment by jjhayes** [comment] 2016-05-27 21:07
I just noted that you've only allocated 16G to the / partition, which is going to include /opt--where the sdsc rolls install all of their software.  That's not going to hold much of the installation.  As a work-around, you can do

mv /opt /state/partition1/
ln -s /state/partition1/opt /

to place /opt onto your larger partition.

**Comment by ivannovikov** [comment] 2016-05-27 21:14
Jim,

Unfortunately, at that point, I am lost. I didn't really allocate 16G to the / partition, I merely follow instructions for the Rocks 6.2 installation. Do you mean that during Rocks 6.2 installation I will be asked to allocate space for the partition and at that point I should enter more space there?

Ivan

**Comment by jjhayes** [comment] 2016-05-27 21:37
During the Rocks installation, we generally allocate a significant portion of the hard disk to the / and /var partitions--128GB and 64GB, respectively, in the case of the cluster that I manage.  SDSC's full /opt s/w stack  looks to be around 55GB installed.  That's likely far more than you're trying to install, but even a handful of rolls will use up 16GB pretty quickly.  `du -sh /opt/*` will show you how much space each of the /opt packages is presently occupying.

If you don't want to reinstall, the mv/ln approach I noted above is probably the easiest approach.   Instead of moving all of /opt, you might want to move only individual applications that take up a lot of space, e.g.,

mkdir /state/partition1/opt
mv /opt/gnu /state/partition1/opt/
ln -s /state/partition1/opt/gnu /opt/gnu

I sometimes take this approach with the Intel compilers, which take up 11GB.

Jim

**Comment by ivannovikov** [comment] 2016-05-27 22:51
Jim,

It looks like 16GB is a standard: http://www.rocksclusters.org/roll-documentation/base/5.5/install-frontend.html

Do I understand you correctly, that during the Rocks 6.2 installation process I should pick up "Manual Partition" option instead of "Auto partition"?

Ivan

**Comment by jjhayes** [comment] 2016-06-14 17:49
Because we've tracked this down to a problem outside the roll source, I'm going to go ahead and close the issue.

Jim

**Closed as completed** 2016-06-14 20:47 UTC
